-- LAB #12-2: CONCURRENT TRANSACTIONS - 001
COLUMN Bookname format a10;
SET TRANSACTION NAME 'lab12_t1';

SELECT * FROM BOOK WHERE bookid = 1;
UPDATE BOOK SET price = 20000 WHERE bookid = 1;

SELECT * FROM BOOK WHERE bookid = 1;
COMMIT;

-- LAB #12-2: CONCURRENT TRANSACTIONS - 002
COLUMN Bookname format a10;
SET TRANSACTION NAME 'lab12_t2';

SELECT * FROM BOOK WHERE bookid = 1;
UPDATE BOOK SET price = price + 1000 WHERE bookid = 1;

SELECT * FROM BOOK WHERE bookid = 1;
COMMIT;